### ISSUE TITLE
Do we need to download and install the "Android Wear - Smartwatch" App too?

### ISSUE THREAD

**Issue by deliverymanager** [bevkoski/react-native-android-wear-demo#1]
Do we need to download and install in the phone the "Android Wear - Smartwatch" App from Google Play in order to pair the two devices?

Thank you!

**Comment by bevkoski** [comment]
@deliverymanager, yes, you will have to first pair the devices in order for them to be able to communicate between each other.

**Comment by deliverymanager** [comment]
Thank you for your answer.

OK so from your experience the default way would be to pair the two devices and then communicate.

Do you think there might be a way that the Android Wear - Smartwatch app could provide information from the smartwatch without an app?
For example GPS position of the smartwatch, accelerometer, pulse?

What I mean, is that if there might be a way to get those information without actually having a custom smartphone app.

Thank you!

**Comment by bevkoski** [comment]
There might be a way. I haven't tried to do something like that. Maybe [this](https://stackoverflow.com/questions/42948984/connect-with-moto-360-without-android-wear-app) thread will help you a bit.
